apiVersion: v1
kind: Namespace
metadata:
  name: apps

---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: go-app
  name: go-app
  namespace: apps

---

apiVersion: v1
kind: Secret
metadata:
  name: go-app-svca-token
  namespace: apps
  annotations:
    kubernetes.io/service-account.name: "go-app"
type: kubernetes.io/service-account-token

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-app
  name: go-app
  namespace: apps
spec:
  selector:
    matchLabels:
      app: go-app
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: go-app
    spec:
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        runAsGroup: 1000
      containers:
        - name: go-app
          image: babbili/vault-go:54edf0ba9
          imagePullPolicy : Always       
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            privileged: false
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          ports:
          - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 4
            failureThreshold: 8
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 8
            failureThreshold: 16
          env:
            - name: ROLE_ID
              valueFrom:
                secretKeyRef:
                  name: approle
                  key: role-id     
      serviceAccount: go-app
      serviceAccountName: go-app

